-- Initial PostgreSQL migration. Apply with: psql "$DATABASE_URL" -f alembic/versions/0001_initial.sql
-- SQLAlchemy creates the development schema at startup; production should run reviewed migrations only.
CREATE TABLE IF NOT EXISTS users (id varchar PRIMARY KEY,email varchar UNIQUE NOT NULL,full_name varchar NOT NULL,password_hash varchar NOT NULL,role varchar NOT NULL DEFAULT 'CUSTOMER',verified_at timestamp,created_at timestamp NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS quote_requests (id varchar PRIMARY KEY,number varchar UNIQUE NOT NULL,user_id varchar REFERENCES users(id),medicine varchar NOT NULL,strength varchar NOT NULL,form varchar NOT NULL,quantity integer NOT NULL,notes text,status varchar NOT NULL DEFAULT 'PENDING_REVIEW',draft_order_id varchar,created_at timestamp NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS quotes (id varchar PRIMARY KEY,number varchar UNIQUE NOT NULL,request_id varchar REFERENCES quote_requests(id),user_id varchar REFERENCES users(id),status varchar NOT NULL,medicine_price numeric(12,2) NOT NULL,shipping numeric(12,2) NOT NULL DEFAULT 0,service_fee numeric(12,2) NOT NULL DEFAULT 0,expires_at timestamp NOT NULL,created_at timestamp NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS orders (id varchar PRIMARY KEY,number varchar UNIQUE NOT NULL,user_id varchar REFERENCES users(id),status varchar NOT NULL,checkout_session_id varchar UNIQUE,address jsonb,created_at timestamp NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS order_items (id varchar PRIMARY KEY,order_id varchar REFERENCES orders(id),quote_id varchar UNIQUE REFERENCES quotes(id),medicine varchar NOT NULL,quantity integer NOT NULL,medicine_price_snapshot numeric(12,2) NOT NULL,shipping_snapshot numeric(12,2) NOT NULL,service_fee_snapshot numeric(12,2) NOT NULL);
CREATE TABLE IF NOT EXISTS documents (id varchar PRIMARY KEY,order_id varchar REFERENCES orders(id),user_id varchar REFERENCES users(id),kind varchar NOT NULL,storage_key varchar UNIQUE NOT NULL,checksum varchar NOT NULL,status varchar NOT NULL,created_at timestamp NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS payments (id varchar PRIMARY KEY,order_id varchar REFERENCES orders(id),stripe_session_id varchar UNIQUE NOT NULL,stripe_payment_intent_id varchar,amount numeric(12,2) NOT NULL,currency varchar NOT NULL,status varchar NOT NULL,created_at timestamp NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_events (id varchar PRIMARY KEY,actor_id varchar,actor_role varchar,event_type varchar NOT NULL,entity_type varchar NOT NULL,entity_id varchar NOT NULL,success boolean NOT NULL,metadata jsonb,created_at timestamp NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS webhook_events (id varchar PRIMARY KEY,received_at timestamp NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS password_reset_tokens (id varchar PRIMARY KEY,user_id varchar NOT NULL REFERENCES users(id),token_hash varchar UNIQUE NOT NULL,expires_at timestamp NOT NULL,used_at timestamp,created_at timestamp NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ix_password_reset_tokens_user_id ON password_reset_tokens (user_id);
CREATE INDEX IF NOT EXISTS ix_password_reset_tokens_token_hash ON password_reset_tokens (token_hash);
