import uuid
from datetime import datetime
from sqlalchemy import String, DateTime, ForeignKey, Numeric, Text, JSON, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from .database import Base
def uid(): return str(uuid.uuid4())
class User(Base):
    __tablename__='users'; id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); email: Mapped[str]=mapped_column(String, unique=True, index=True); full_name: Mapped[str]=mapped_column(String); password_hash: Mapped[str]=mapped_column(String); role: Mapped[str]=mapped_column(String, default='CUSTOMER'); phone: Mapped[str|None]=mapped_column(String, nullable=True); address: Mapped[dict|None]=mapped_column(JSON, nullable=True); agreement_version: Mapped[str|None]=mapped_column(String, nullable=True); agreement_accepted_at: Mapped[datetime|None]=mapped_column(DateTime, nullable=True); verified_at: Mapped[datetime|None]=mapped_column(DateTime, nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow)
class QuoteRequest(Base):
    __tablename__='quote_requests'; id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); number: Mapped[str]=mapped_column(String, unique=True); user_id: Mapped[str]=mapped_column(ForeignKey('users.id')); medicine: Mapped[str]=mapped_column(String); strength: Mapped[str]=mapped_column(String); form: Mapped[str]=mapped_column(String); quantity: Mapped[int]; notes: Mapped[str|None]=mapped_column(Text, nullable=True); status: Mapped[str]=mapped_column(String, default='PENDING_REVIEW'); draft_order_id: Mapped[str|None]=mapped_column(String, nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow)
class Quote(Base):
    __tablename__='quotes'; id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); number: Mapped[str]=mapped_column(String, unique=True); request_id: Mapped[str]=mapped_column(ForeignKey('quote_requests.id')); user_id: Mapped[str]=mapped_column(ForeignKey('users.id')); status: Mapped[str]=mapped_column(String, default='DRAFT'); medicine_price: Mapped[float]=mapped_column(Numeric(12,2)); shipping: Mapped[float]=mapped_column(Numeric(12,2), default=0); service_fee: Mapped[float]=mapped_column(Numeric(12,2), default=0); expires_at: Mapped[datetime]=mapped_column(DateTime); created_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow)
class QuoteGroup(Base):
    __tablename__='quote_groups'; id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); number: Mapped[str]=mapped_column(String, unique=True); user_id: Mapped[str]=mapped_column(ForeignKey('users.id')); status: Mapped[str]=mapped_column(String, default='PENDING_REVIEW'); created_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow)
class QuoteGroupRequest(Base):
    __tablename__='quote_group_requests'; id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); group_id: Mapped[str]=mapped_column(ForeignKey('quote_groups.id')); request_id: Mapped[str]=mapped_column(ForeignKey('quote_requests.id'), unique=True)
class QuoteGroupQuote(Base):
    __tablename__='quote_group_quotes'; id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); group_id: Mapped[str]=mapped_column(ForeignKey('quote_groups.id')); quote_id: Mapped[str]=mapped_column(ForeignKey('quotes.id'), unique=True)
class Order(Base):
    __tablename__='orders'; id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); number: Mapped[str]=mapped_column(String, unique=True); user_id: Mapped[str]=mapped_column(ForeignKey('users.id')); status: Mapped[str]=mapped_column(String, default='DRAFT'); checkout_session_id: Mapped[str|None]=mapped_column(String, unique=True, nullable=True); address: Mapped[dict|None]=mapped_column(JSON, nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow)
class OrderItem(Base):
    __tablename__='order_items'; id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); order_id: Mapped[str]=mapped_column(ForeignKey('orders.id')); quote_id: Mapped[str]=mapped_column(ForeignKey('quotes.id'), unique=True); medicine: Mapped[str]=mapped_column(String); quantity: Mapped[int]; medicine_price_snapshot: Mapped[float]=mapped_column(Numeric(12,2)); shipping_snapshot: Mapped[float]=mapped_column(Numeric(12,2)); service_fee_snapshot: Mapped[float]=mapped_column(Numeric(12,2))
class Document(Base):
    __tablename__='documents'; id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); order_id: Mapped[str]=mapped_column(ForeignKey('orders.id')); user_id: Mapped[str]=mapped_column(ForeignKey('users.id')); kind: Mapped[str]=mapped_column(String); storage_key: Mapped[str]=mapped_column(String, unique=True); checksum: Mapped[str]=mapped_column(String); status: Mapped[str]=mapped_column(String, default='PENDING_SCAN'); created_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow)
class Payment(Base):
    __tablename__='payments'; id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); order_id: Mapped[str]=mapped_column(ForeignKey('orders.id')); stripe_session_id: Mapped[str]=mapped_column(String, unique=True); stripe_payment_intent_id: Mapped[str|None]=mapped_column(String, nullable=True); amount: Mapped[float]=mapped_column(Numeric(12,2)); currency: Mapped[str]=mapped_column(String); status: Mapped[str]=mapped_column(String); created_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow)
class AuditEvent(Base):
    __tablename__='audit_events'; id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); actor_id: Mapped[str|None]=mapped_column(String, nullable=True); actor_role: Mapped[str|None]=mapped_column(String, nullable=True); event_type: Mapped[str]=mapped_column(String); entity_type: Mapped[str]=mapped_column(String); entity_id: Mapped[str]=mapped_column(String); success: Mapped[bool]; metadata_: Mapped[dict|None]=mapped_column('metadata', JSON, nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow)
class WebhookEvent(Base):
    __tablename__='webhook_events'; id: Mapped[str]=mapped_column(String, primary_key=True); received_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow)
class PasswordResetToken(Base):
    __tablename__='password_reset_tokens'; id: Mapped[str]=mapped_column(String, primary_key=True, default=uid); user_id: Mapped[str]=mapped_column(ForeignKey('users.id'), index=True); token_hash: Mapped[str]=mapped_column(String, unique=True, index=True); expires_at: Mapped[datetime]=mapped_column(DateTime, nullable=False); used_at: Mapped[datetime|None]=mapped_column(DateTime, nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow)
